Repository overit-official/tomcat-redis-manager, pull requests merged in 2022-05, with the labels that each got.

#8 Session draining on demand
  pom.xml
  src/main/java/com/overit/tomcat/redis/RedisConnector.java
  src/main/java/com/overit/tomcat/redis/RedisStore.java
  src/main/java/com/overit/tomcat/redis/RedisSubscriberService.java
  src/main/java/com/overit/tomcat/redis/RedisSubscriberServiceManager.java
  src/test/java/com/overit/tomcat/redis/RedisStoreTest.java
Labels: enhancement

#9 session draining on demand - little improvement
  src/main/java/com/overit/tomcat/redis/RedisStore.java
Labels: enhancement

#10 version 1.1.6
  pom.xml
Labels: new version

#11 finor fix
  src/main/java/com/overit/tomcat/redis/RedisStore.java
  src/test/java/com/overit/tomcat/redis/RedisStoreTest.java
Labels: bug

#12 lazily register the subscriber
  src/main/java/com/overit/tomcat/redis/RedisStore.java
  src/main/java/com/overit/tomcat/redis/RedisSubscriberService.java
  src/main/java/com/overit/tomcat/redis/RedisSubscriberServiceManager.java
  src/test/java/com/overit/tomcat/redis/RedisStoreTest.java
Labels: bug

#13 Session Passivation process
  src/main/java/com/overit/tomcat/redis/RedisStore.java
  src/test/java/com/overit/tomcat/redis/RedisManagerTest.java
  src/test/java/com/overit/tomcat/redis/RedisStoreTest.java
Labels: bug

#14 increase code coverage
  pom.xml
  src/main/java/com/overit/tomcat/redis/RedisConnector.java
  src/main/java/com/overit/tomcat/redis/RedisStore.java
  src/main/java/com/overit/tomcat/redis/RedisSubscriberService.java
  src/main/java/com/overit/tomcat/redis/RedisSubscriberServiceManager.java
  src/test/java/com/overit/tomcat/redis/RedisConnectorTest.java
  src/test/java/com/overit/tomcat/redis/RedisStoreTest.java
Labels: documentation, enhancement

#15 [GC-670] update docker-ci workflow to add the jar artifact to each Gi…
  .github/workflows/docker-ci.yml
Labels: enhancement
